# -*- coding: utf-8 -*-
"""ShipRag_accurate_(97.26%) ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VWHwCa_yDceToWn_OrxQH2N4Zo7SuuK

**Import Required Libraries**
"""

!pip install -U langchain langchain-community sentence-transformers faiss-cpu rank_bm25 transformers accelerate pypdf unstructured

import torch
print(torch.cuda.is_available())

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings, OllamaEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.retrievers import BM25Retriever
from langchain_community.llms import Ollama

from sentence_transformers import CrossEncoder
from transformers import pipeline

"""**Ollama Setup**"""

!apt-get update -qq
!apt-get install -y zstd
!sudo apt update
!sudo apt install -y pciutils
!curl -fsSL https://ollama.com/install.sh | sh

import threading
import subprocess
import time

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()
time.sleep(5)

!ollama pull llama3:8b
!ollama pull mxbai-embed-large
!ollama list

"""**Load PDF Document**"""

loader = PyPDFLoader("/content/2 REFRIGERANT MANAGEMENT PLAN.pdf")
pages = loader.load()

"""**Extract Text from PDF Pages**"""

page_texts = []

for page in pages:
    page_texts.append(page.page_content)

print("Text pages extracted:", len(page_texts))

"""CLEAN PDF TEXT (REMOVE HEADERS, FOOTERS, PAGE NOISE)"""

def clean_text(text):

    # Remove page numbers
    text = re.sub(r'Page\s*\d+', '', text)

    # Remove footer line
    text = re.sub(r'Printed by Hanwha Ocean[^\n]*', '', text)

    # Remove Adobe notice
    text = re.sub(r'Document must be opened with Adobe to view all ABS amendments\.', '', text)

    # Remove repeated headers
    text = re.sub(r'Refrigerant Management Plan', '', text)

    # Remove timestamps
    text = re.sub(r'\d{4}-\d{2}-\d{2} \d{2}:\d{2}', '', text)

    # Remove Adobe notice multiline
    text = re.sub(r'Document must.*?amendments\.', '', text, flags=re.DOTALL)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    # Fix broken lines
    text = text.replace('\n', ' ')

    # Strip spaces
    text = text.strip()

    return text

import re

clean_pages = []

for page in page_texts:
    cleaned = clean_text(page)
    clean_pages.append(cleaned)

print("Total cleaned pages:", len(clean_pages))

"""Create LangChain Documents from Cleaned PDF Pages"""

from langchain_core.documents import Document

documents = []

for i, text in enumerate(clean_pages):

    doc = Document(
        page_content=text,
        metadata={"page": i + 1}
    )

    documents.append(doc)

print("Documents created:", len(documents))

"""Chunk the Document"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=512,
    chunk_overlap=100,
    separators=["\n\n", "\n", " ", ""]

)
docs = text_splitter.split_documents(documents)

"""Create Embeddings"""

embedding_model = OllamaEmbeddings(
        model="mxbai-embed-large"
    )

"""Create Vector Database (FAISS)"""

vector_db = FAISS.from_documents(docs, embedding_model)

vector_retriever = vector_db.as_retriever(
    search_kwargs={"k":7}
)

"""Create BM25 Retriever"""

bm25_retriever = BM25Retriever.from_documents(docs)
bm25_retriever.k = 7

"""H**ybrid Retrieval (Vector + BM25)**"""

def hybrid_retrieve(query):

    vec_docs = vector_retriever.invoke(query)
    bm_docs = bm25_retriever.invoke(query)

    docs = vec_docs + bm_docs

    # remove duplicates
    unique = {d.page_content: d for d in docs}

    return list(unique.values())

"""**Cross-Encoder Reranker**"""

reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

def rerank(query, docs, top_k=2):

    pairs = [(query, d.page_content) for d in docs]

    scores = reranker.predict(pairs)

    ranked = sorted(
        zip(scores, docs),
        key=lambda x: x[0],
        reverse=True
    )

    return [doc for _, doc in ranked[:top_k]]

"""LLM (Ollama)"""

from langchain_community.llms import Ollama

qa_model = Ollama(
    model="llama3:8b",
    temperature=0
)

"""Structured Prompt"""

def build_prompt(context, question):

    prompt = f"""
You are an expert assistant answering questions from a ship manual.

Use ONLY the provided context to answer.

If the answer is not present, say:
"Answer not found in document."

Context:
{context}

Question:
{question}

Answer clearly and concisely.
Also mention the page numbers if available.
"""

    return prompt

"""Final ask_question() Function"""

def ask_question(query):

    # Step 1: Hybrid Retrieval
    docs = hybrid_retrieve(query)

    # Step 2: Rerank
    docs = rerank(query, docs)

    # Step 3: Prepare Context
    context = "\n\n".join(
        f"[Page {d.metadata.get('page', 'N/A')}]\n{d.page_content}"
        for d in docs
    )

    # Step 4: Prompt
    prompt = build_prompt(context, query)

    # Step 5: LLM
    response = qa_model.invoke(prompt)

    return response

query =  "What is the purpose of the Refrigerant Management Plan?"


answer = ask_question(query)
print("question\n",query )

print("answer\n",answer)

"""**RAG System Performance Evaluation Report**

Total Questions: 31

Accuracy Distribution

100% → 24 questions

95% → 3 questions

90% → 3 questions

85% → 1 question

Evaluation results (31 questions, 97.26% accuracy)

**Tools and Libraries Used**

 Framework       | LangChain           
 LLM             | Ollama (llama3:8b)  
 Vector Database | FAISS               
 Embedding Model | ollama(mxbai-embed-large )

Data File Link:
https://drive.google.com/file/d/1Y_6Q7yZF4Se6AxyEG20gqMMRF_hu0m9m/view?usp=drive_link
"""